const blending_modes = [
  { value: 1, label: "ALPHA" },
  { value: 0, label: "ADD" },
  { value: 2, label: "AVERAGE" },
  { value: 3, label: "COLOR_BURN" },
  { value: 4, label: "COLOR_DODGE" },
  { value: 5, label: "COLOR" },
  { value: 6, label: "DARKEN" },
  { value: 7, label: "DIFFERENCE" },
  { value: 8, label: "DIVIDE" },
  { value: 9, label: "EXCLUSION" },
  { value: 10, label: "HARD_LIGHT" },
  { value: 11, label: "HARD_MIX" },
  { value: 12, label: "HUE" },
  { value: 13, label: "INVERT_RGB" },
  { value: 14, label: "INVERT" },
  { value: 15, label: "LIGHTEN" },
  { value: 16, label: "LINEAR_BURN" },
  { value: 17, label: "LINEAR_DODGE" },
  { value: 18, label: "LINEAR_LIGHT" },
  { value: 19, label: "LUMINOSITY" },
  { value: 20, label: "MULTIPLY" },
  { value: 21, label: "NEGATION" },
  { value: 22, label: "NORMAL" },
  { value: 23, label: "OVERLAY" },
  { value: 24, label: "PIN_LIGHT" },
  { value: 25, label: "REFLECT" },
  { value: 26, label: "SATURATION" },
  { value: 27, label: "SCREEN" },
  { value: 28, label: "SOFT_LIGHT" },
  { value: 29, label: "SRC" },
  { value: 30, label: "SUBTRACT" },
  { value: 31, label: "VIVID_LIGHT" },
];
export default blending_modes;
